id: A58F2ED85
base_file: f39B4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:31:35.858263
  last_modified_at: 2022-06-17 11:31:35.858266
