id: A58F2ED85
base_file: fE286.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:31:35.883447
  last_modified_at: 2022-06-17 11:31:35.883449
