id: A58F2ED85
base_file: f3362.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:31:35.855298
  last_modified_at: 2022-06-17 11:31:35.855301
