id: A58F2ED85
base_file: fDDB8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:31:35.882078
  last_modified_at: 2022-06-17 11:31:35.882094
