id: A58F2ED85
base_file: fC60A.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:31:35.875969
  last_modified_at: 2022-06-17 11:31:35.875973
