id: A58F2ED85
base_file: f2714.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:31:35.846413
  last_modified_at: 2022-06-17 11:31:35.846420
